### ISSUE TITLE
cifar10 dataset "Maximum allowed size exceeded" Error

### ISSUE THREAD

**Issue by zerok01** [naturomics/CapsLayer#39]
Hi,  
According to the tutorials I made the arrangements for the cifar10 data set. I'm using MatrixCapsNet as a model. Then I started training. After getting up to step 499, I get the following error (I decreased the batch size up to 1, but the result is the same). What is the solution to this?

>  step: 491, loss: 0.425, time: 0.034 sec/step
 step: 492, loss: 0.425, time: 0.034 sec/step
 step: 493, loss: 0.427, time: 0.033 sec/step
 step: 494, loss: 0.425, time: 0.034 sec/step
 step: 495, loss: 0.366, time: 0.033 sec/step
 step: 496, loss: 0.433, time: 0.034 sec/step
 step: 497, loss: 0.374, time: 0.033 sec/step
 step: 498, loss: 0.358, time: 0.034 sec/step
 step: 499, loss: 0.382, time: 0.033 sec/step
evaluating, it will take a while...
Traceback (most recent call last):
  File "main.py", line 237, in <module>
    tf.app.run()
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 231, in main
    train(net, data_loader)
  File "main.py", line 137, in train
    plot_activation(np.hstack((probs, targets)), step=step, save_to=path)
  File "/home/atakan/.local/lib/python3.6/site-packages/capslayer-0.1.5-py3.6.egg/capslayer/plotlib/figure.py", line 52, in plot_activation
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 222, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 545, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1144, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2426, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1136, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 969, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 969, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 912, in iter_ticks
    majorLocs = self.major.locator()
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/ticker.py", line 1367, in __call__
    return self.tick_values(dmin, dmax)
  File "/home/atakan/anaconda3/lib/python3.6/site-packages/matplotlib/ticker.py", line 1371, in tick_values
    np.arange(vmin + self.offset, vmax + 1, self._base))
ValueError: Maximum allowed size exceeded

**Comment by naturomics** [comment]
I am not sure what causes this error now, you can comment out this [line](https://github.com/naturomics/CapsLayer/blob/926ee89803dad3c273eafcd31a60718ddb9dad8d/models/main.py#L137) to keep training. The function called in that line just plots a figure like [this one](https://github.com/naturomics/CapsLayer/blob/master/models/assets/results_mnist_vecCapsNetactivations.gif), it is not necessary for training the model.

**Comment by zerok01** [comment]
I comment out it because I thought it was not necessary. Maybe I asked if the problem could be solved. Anyway, thanks. You can close this issue.
